apiVersion: v1
kind: Secret
metadata:
  name: backend-config
  namespace: default
type: Opaque
data:
  DATABASE_URI: bXlzcWwrcHlteXNxbDovL2FkbWluZXI6YWRtaW5lcjEyMzRAbWljcm9zZXJ2aWNlcy1leGFtcGxlLmNnZndiZWRqdmh3cC5ldS1jZW50cmFsLTEucmRzLmFtYXpvbmF3cy5jb206MzMwNi9tYWlu