apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: random9deploy/ms-admin:1.0
          command:
            - sh
            - -c
            - |
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              value: admin
            - name: DB_USER
              value: adminer
            - name: DB_PASSWORD
              value: adminer1234
            - name: DB_HOST
              value: microservices-example.cgfwbedjvhwp.eu-central-1.rds.amazonaws.com
            - name: DB_PORT
              value: "3306"
            - name: RABBITMQ_URL
              value: amqps://omzxrsxb:KfqhZsJnf3XDVdjM_9MM5m4hW2BtKA_U@cow.rmq2.cloudamqp.com/omzxrsxb