apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-queue
spec:
  selector:
    matchLabels:
      app: admin-queue
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-queue
    spec:
      containers:
        - name: admin-queue
          image: random9deploy/ms-admin:1.0
          env:
            - name: RABBITMQ_URL
              value: amqps://omzxrsxb:KfqhZsJnf3XDVdjM_9MM5m4hW2BtKA_U@cow.rmq2.cloudamqp.com/omzxrsxb
          command: ["python", "-u", "consumer.py"]
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"

